# -*- coding: utf-8 -*-
"""topsis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jV9pZl8vqxQS5logV7cY3WBOAsWoXbX7
"""

import sys
import pandas as pd
import numpy as np
import os

def checkInputs(inputFileName, weights, impacts, resultFileName):
    if not os.path.isfile(inputFileName):
        print(f"Error: File {inputFileName} not found")
        sys.exit(1)
    try:
        dataSet = pd.read_csv(inputFileName)
    except Exception:
        print("Error: Could not read input file")
        sys.exit(1)
    if len(dataSet.columns) < 3:
        print("Error: Input file must contain three or more columns")
        sys.exit(1)
    try:
        tempData = dataSet.iloc[:, 1:].astype(float)
    except ValueError:
        print("Error: From 2nd to last columns must contain numeric values only")
        sys.exit(1)
    weightList = [float(w) for w in weights.split(',')]
    impactList = impacts.split(',')
    if len(weightList) != len(impactList) or len(weightList) != len(tempData.columns):
        print("Error: Number of weights, number of impacts and number of columns must be the same")
        sys.exit(1)
    if not all(i in ['+', '-'] for i in impactList):
        print("Error: Impacts must be either +ve or -ve")
        sys.exit(1)
    return dataSet, tempData, weightList, impactList

def calculateTopsis(dataSet, tempData, weights, impacts, resultFileName):
    matrix = tempData.values
    rows, cols = matrix.shape
    normMatrix = matrix / np.sqrt((matrix**2).sum(axis=0))
    weightedMatrix = normMatrix * weights
    idealBest = []
    idealWorst = []
    for i in range(cols):
        if impacts[i] == '+':
            idealBest.append(max(weightedMatrix[:, i]))
            idealWorst.append(min(weightedMatrix[:, i]))
        else:
            idealBest.append(min(weightedMatrix[:, i]))
            idealWorst.append(max(weightedMatrix[:, i]))
    euclideanDistanceBest = np.sqrt(((weightedMatrix - idealBest)**2).sum(axis=1))
    euclideanDistanceWorst = np.sqrt(((weightedMatrix - idealWorst)**2).sum(axis=1))
    performanceScore = euclideanDistanceWorst / (euclideanDistanceBest + euclideanDistanceWorst)
    dataSet['Topsis Score'] = performanceScore
    dataSet['Rank'] = dataSet['Topsis Score'].rank(ascending=False)
    dataSet.to_csv(resultFileName, index=False)
    print(f"Result saved to {resultFileName}")

def main():
    if len(sys.argv) != 5:
        print("Usage: python topsis.py <InputDataFile> <Weights> <Impacts> <OutputResultFileName>")
        sys.exit(1)
    inputFileName = sys.argv[1]
    weights = sys.argv[2]
    impacts = sys.argv[3]
    resultFileName = sys.argv[4]
    originalData, processedData, weightList, impactList = checkInputs(inputFileName, weights, impacts, resultFileName)
    calculateTopsis(originalData, processedData, weightList, impactList, resultFileName)

if __name__ == "__main__":
    main()



