# -*- coding: utf-8 -*-
"""setup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xu9Do8xux7vYeFPYo7isoiogTA6O0-Ie
"""

from setuptools import setup, find_packages

setup(
    name="topsis_abhishek_102317167",   # <--- CHANGED TO UNDERSCORES
    version="2.0.1",                    # <--- Bumped version
    author="Abhishek",
    author_email="apanchal_be23@thapar.edu",
    description="A package for TOPSIS implementation",
    long_description="A Python package for TOPSIS",
    long_description_content_type="text/markdown",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
    entry_points={
        'console_scripts': [
            'topsis-abhishek-102317167=topsis_abhishek_102317167:main',
        ],
    },
)